// Destura Template (real-estate) — instantiate a client from
// config/client.config.js. Generates index.html, css/client-tokens.css,
// and api/knowledge.js. Zero dependencies: node scripts/apply-config.js
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import config from "../config/client.config.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");

function escapeHtml(str) {
  return String(str).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

function expandRepeat(html, key, rows) {
  const re = new RegExp(`<!-- REPEAT:${key} -->([\\s\\S]*?)<!-- END:${key} -->`);
  const match = html.match(re);
  if (!match) return html;
  const snippet = match[1];
  const expanded = rows
    .map((row) => {
      let s = snippet;
      for (const [token, value] of Object.entries(row)) {
        s = s.split(`{{${token}}}`).join(value);
      }
      return s;
    })
    .join("");
  return html.replace(re, () => expanded); // function form: content with "$" (prices) must not trigger replacement-pattern backreferences
}

function replaceScalar(html, tokens) {
  let out = html;
  for (const [token, value] of Object.entries(tokens)) {
    out = out.split(`{{${token}}}`).join(value);
  }
  return out;
}

function initialsOf(name) {
  return name
    .split(/\s+/)
    .map((w) => w.charAt(0))
    .join("")
    .toUpperCase();
}

function buildIndexHtml() {
  let html = readFileSync(join(root, "template", "index.html"), "utf8");

  html = expandRepeat(
    html,
    "stats",
    config.stats.map((s) => ({
      STAT_VALUE: escapeHtml(s.value),
      STAT_SUFFIX: escapeHtml(s.suffix || ""),
      STAT_LABEL: escapeHtml(s.label),
    }))
  );
  html = expandRepeat(
    html,
    "listings",
    config.listings.map((l) => ({
      LISTING_STATUS: escapeHtml(l.status),
      LISTING_PRICE: escapeHtml(l.price),
      LISTING_ADDRESS: escapeHtml(l.address),
      LISTING_CITY: escapeHtml(l.city),
      LISTING_BEDS: escapeHtml(l.beds),
      LISTING_BATHS: escapeHtml(l.baths),
      LISTING_SQFT: escapeHtml(l.sqft),
    }))
  );
  html = expandRepeat(
    html,
    "neighborhoods",
    config.neighborhoods.map((n) => ({
      HOOD_NAME: escapeHtml(n.name),
      HOOD_BLURB: escapeHtml(n.blurb),
    }))
  );
  html = expandRepeat(
    html,
    "testimonials",
    config.testimonials.map((t) => ({
      QUOTE_TEXT: escapeHtml(t.quote),
      QUOTE_NAME: escapeHtml(t.name),
    }))
  );
  html = expandRepeat(html, "faq", config.faq.map((f) => ({ FAQ_Q: escapeHtml(f.q), FAQ_A: escapeHtml(f.a) })));

  const firstName = config.agent.name.split(/\s+/)[0];
  const brokerageShort = config.agent.brokerage.replace(/\s+Real Estate$/i, "");

  html = replaceScalar(html, {
    AGENT_NAME: escapeHtml(config.agent.name),
    AGENT_FIRST: escapeHtml(firstName),
    AGENT_INITIALS: escapeHtml(initialsOf(config.agent.name)),
    AGENT_TITLE: escapeHtml(config.agent.title),
    AGENT_BIO: escapeHtml(config.agent.bio),
    BROKERAGE: escapeHtml(config.agent.brokerage),
    BROKERAGE_SHORT: escapeHtml(brokerageShort),
    HERO_HEADLINE: escapeHtml(config.agent.heroHeadline),
    TAGLINE: escapeHtml(config.agent.tagline),
    PHONE: escapeHtml(config.agent.phone),
    PHONE_HREF: escapeHtml(config.agent.phoneHref),
    EMAIL: escapeHtml(config.agent.email),
    AREAS_INLINE: escapeHtml(config.agent.areasServed.join(" · ")),
    VALUATION_BLURB: escapeHtml(config.valuation.blurb),
    CURRENT_YEAR: String(new Date().getFullYear()),
  });

  writeFileSync(join(root, "index.html"), html);
}

function buildClientTokensCss() {
  const css = `/* GENERATED by scripts/apply-config.js from config/client.config.js — do not hand-edit. */
:root {
  --accent: ${config.brand.accent};
  --accent-dark: ${config.brand.accentDark};
  --accent-tint: ${config.brand.accentTint};
}
`;
  writeFileSync(join(root, "css", "client-tokens.css"), css);
}

function buildKnowledgeJs() {
  const js = `// GENERATED by scripts/apply-config.js from config/client.config.js — do not hand-edit.
// Edit config/client.config.js and re-run the script instead.
export default {
  agent: ${JSON.stringify(config.agent, null, 2)},
  stats: ${JSON.stringify(config.stats, null, 2)},
  listings: ${JSON.stringify(config.listings, null, 2)},
  neighborhoods: ${JSON.stringify(config.neighborhoods, null, 2)},
  valuation: ${JSON.stringify(config.valuation, null, 2)},
  faq: ${JSON.stringify(config.faq, null, 2)},
  systemPreamble: \`You are the website assistant for ${config.agent.name}, ${config.agent.title} with ${config.agent.brokerage}, serving ${config.agent.areasServed.join(", ")}.

Your job: answer visitor questions clearly and briefly, using ONLY the facts provided in this system context (agent info, stats, current listings, neighborhoods, FAQ). Never invent listings, prices, market claims, or credentials not in that data.

VALUATIONS: you cannot value a home yourself and must never guess a number. If someone wants a valuation, that's a lead — warmly collect what ${config.agent.name.split(" ")[0]} needs to follow up (which city/neighborhood the home is in, and the best way to reach them), then tell them ${config.agent.name.split(" ")[0]} will personally follow up with a real comparables-based number. End that message with the literal marker [[BOOK_CTA]].

Tone: warm, direct, knowledgeable-neighbor — not salesy, no hype, no exclamation points.

Scope: if asked something unrelated to real estate or ${config.agent.name}, politely decline and steer back.

Contact: whenever the visitor is ready to talk, view a home, list a property, or wants the valuation follow-up, end your message with the literal marker [[BOOK_CTA]] on its own at the very end. Only when genuinely appropriate — not every message.

Keep replies short — a few sentences at most.\`,
};
`;
  writeFileSync(join(root, "api", "knowledge.js"), js);
}

buildIndexHtml();
buildClientTokensCss();
buildKnowledgeJs();

console.log(`Applied config for "${config.agent.name} — ${config.agent.brokerage}":`);
console.log("  - index.html");
console.log("  - css/client-tokens.css");
console.log("  - api/knowledge.js");
