// GENERATED by scripts/apply-config.js from config/client.config.js — do not hand-edit.
// Edit config/client.config.js and re-run the script instead.
export default {
  company: {
  "name": "TIGER Floors",
  "shortName": "TIGER",
  "category": "Flooring Installation",
  "tagline": "Walk in proud.",
  "heroHeadline": "Walk in proud of your new floor.",
  "subhead": "Hardwood, laminate, vinyl, and tile installation for Coquitlam and the Lower Mainland — every job starts with a free estimate.",
  "phone": "(604) 783-0173",
  "phoneHref": "+16047830173",
  "email": "tigerfloors.sales@gmail.com",
  "city": "Coquitlam, BC",
  "areasServed": "Coquitlam & the Lower Mainland",
  "bio": "TIGER Floors installs hardwood, laminate, vinyl, and tile floors across Coquitlam and the Lower Mainland. Every quote starts with a free, no-pressure estimate — no work gets booked until you've seen a real number."
},
  services: [
  {
    "name": "Hardwood",
    "blurb": "Solid and engineered hardwood installation, built to last and refinish over time.",
    "icon": "plank"
  },
  {
    "name": "Laminate",
    "blurb": "Durable, budget-friendly flooring that holds up to daily life.",
    "icon": "layers"
  },
  {
    "name": "Vinyl",
    "blurb": "Waterproof, low-maintenance flooring for kitchens, baths, and busy households.",
    "icon": "roll"
  },
  {
    "name": "Tile",
    "blurb": "Precision tile installation for kitchens, bathrooms, and entryways.",
    "icon": "grid"
  }
],
  faq: [
  {
    "q": "Do you offer free estimates?",
    "a": "Yes — every job starts with a free, no-obligation estimate before anything gets booked."
  },
  {
    "q": "What types of flooring do you install?",
    "a": "Hardwood, laminate, vinyl, and tile."
  },
  {
    "q": "What areas do you serve?",
    "a": "We're based in Coquitlam and serve the surrounding Lower Mainland — ask us to confirm coverage for your address."
  },
  {
    "q": "How long does an installation take?",
    "a": "It depends on the material and the size of the space. We'll give you a realistic timeline as part of your free estimate."
  },
  {
    "q": "How do I get started?",
    "a": "Call or text (604) 783-0173, email tigerfloors.sales@gmail.com, or ask Tiger right here on the site."
  }
],
  systemPreamble: `You are "Ask Tiger," the website assistant for TIGER Floors, a flooring installer based in Coquitlam, BC, serving Coquitlam & the Lower Mainland.

Your job: answer visitor questions clearly and briefly, using ONLY the facts provided in this system context (company info, services, FAQ). Never invent pricing, timelines, warranty terms, credentials, or licensing claims not in that data.

ESTIMATES: you cannot price a job yourself and must never guess a number. If someone wants a quote, that's a lead — warmly collect what the team needs to follow up (what room/space, which flooring type, and the best way to reach them), then tell them the team will follow up with a real free estimate. End that message with the literal marker [[BOOK_CTA]].

Tone: friendly, plainspoken, a little proud (the company's own tagline is "Walk in proud") — not salesy, no hype, no exclamation-point overload.

Scope: if asked something unrelated to flooring or TIGER Floors, politely decline and steer back.

Contact: whenever the visitor is ready to book an estimate, or has been asking pricing/scheduling questions, end your message with the literal marker [[BOOK_CTA]] on its own at the very end. Only when genuinely appropriate — not every message.

Keep replies short — a few sentences at most.`,
};
