// GENERATED by scripts/apply-config.js from config/client.config.js — do not hand-edit.
// Edit config/client.config.js and re-run the script instead.
export default {
  agent: {
  "name": "Elena Marsh",
  "title": "Fraser Valley Realtor",
  "brokerage": "Marsh & Co. Real Estate",
  "heroHeadline": "Your next chapter starts with the right guide.",
  "tagline": "Buying or selling in the Fraser Valley — local knowledge, honest numbers, and a realtor who answers her phone.",
  "phone": "(604) 555-0119",
  "phoneHref": "+16045550119",
  "email": "elena@marshandco.ca",
  "areasServed": [
    "Abbotsford",
    "Chilliwack",
    "Langley",
    "Mission"
  ],
  "bio": "Fifteen years selling homes where I grew up. I price honestly, negotiate hard, and tell you the things other agents won't — including when not to buy."
},
  stats: [
  {
    "value": "240",
    "suffix": "+",
    "label": "Homes sold"
  },
  {
    "value": "15",
    "suffix": "",
    "label": "Years in the Valley"
  },
  {
    "value": "98",
    "suffix": "%",
    "label": "List-to-sale price"
  },
  {
    "value": "11",
    "suffix": "",
    "label": "Days avg. on market"
  }
],
  listings: [
  {
    "address": "34521 Woodbine Crescent",
    "city": "Abbotsford",
    "price": "$1,149,000",
    "beds": "4",
    "baths": "3",
    "sqft": "2,860",
    "status": "For Sale"
  },
  {
    "address": "8-45766 Chestnut Lane",
    "city": "Chilliwack",
    "price": "$689,000",
    "beds": "3",
    "baths": "2",
    "sqft": "1,540",
    "status": "For Sale"
  },
  {
    "address": "2203 Riverbend Terrace",
    "city": "Langley",
    "price": "$1,395,000",
    "beds": "5",
    "baths": "4",
    "sqft": "3,410",
    "status": "Just Listed"
  },
  {
    "address": "12 Cedarholme Gate",
    "city": "Mission",
    "price": "$874,500",
    "beds": "4",
    "baths": "3",
    "sqft": "2,120",
    "status": "Sold"
  }
],
  neighborhoods: [
  {
    "name": "East Abbotsford",
    "blurb": "Family streets, top school catchments, and the Valley's best sunset views off Sumas Mountain."
  },
  {
    "name": "Sardis & Vedder",
    "blurb": "Chilliwack's fastest-growing pocket — river trails, new builds, and small-town Saturday markets."
  },
  {
    "name": "Willoughby",
    "blurb": "Langley's commuter sweet spot: new townhomes, growing amenities, highway access in minutes."
  }
],
  valuation: {
  "blurb": "Thinking of selling? Most homeowners are two years out of date on what their place is actually worth. Get a real number — based on live comparables, not an online estimate."
},
  faq: [
  {
    "q": "What areas do you cover?",
    "a": "Abbotsford, Chilliwack, Langley, and Mission — the communities I've lived and sold in for fifteen years."
  },
  {
    "q": "What does it cost to work with you as a buyer?",
    "a": "For buyers, my commission is paid by the seller in almost all cases — my guidance costs you nothing out of pocket."
  },
  {
    "q": "How do you decide a listing price?",
    "a": "Live comparables, current buyer demand, and an honest walk-through of your home — not a formula, and never a flattering number just to win the listing."
  },
  {
    "q": "How fast do you respond?",
    "a": "Same day, usually within the hour. Text is fastest. Most deals are won and lost in response time, and I treat it that way."
  },
  {
    "q": "Can I see homes on evenings or weekends?",
    "a": "Yes — most showings happen outside business hours, and I plan around your schedule, not mine."
  }
],
  systemPreamble: `You are the website assistant for Elena Marsh, Fraser Valley Realtor with Marsh & Co. Real Estate, serving Abbotsford, Chilliwack, Langley, Mission.

Your job: answer visitor questions clearly and briefly, using ONLY the facts provided in this system context (agent info, stats, current listings, neighborhoods, FAQ). Never invent listings, prices, market claims, or credentials not in that data.

VALUATIONS: you cannot value a home yourself and must never guess a number. If someone wants a valuation, that's a lead — warmly collect what Elena needs to follow up (which city/neighborhood the home is in, and the best way to reach them), then tell them Elena will personally follow up with a real comparables-based number. End that message with the literal marker [[BOOK_CTA]].

Tone: warm, direct, knowledgeable-neighbor — not salesy, no hype, no exclamation points.

Scope: if asked something unrelated to real estate or Elena Marsh, politely decline and steer back.

Contact: whenever the visitor is ready to talk, view a home, list a property, or wants the valuation follow-up, end your message with the literal marker [[BOOK_CTA]] on its own at the very end. Only when genuinely appropriate — not every message.

Keep replies short — a few sentences at most.`,
};
